/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package itdelatrisu.craq.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Consistency models.
 */
public enum CraqConsistencyModel implements org.apache.thrift.TEnum {
  STRONG(0),
  EVENTUAL(1),
  EVENTUAL_BOUNDED(2),
  DEBUG(3);

  private final int value;

  private CraqConsistencyModel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CraqConsistencyModel findByValue(int value) { 
    switch (value) {
      case 0:
        return STRONG;
      case 1:
        return EVENTUAL;
      case 2:
        return EVENTUAL_BOUNDED;
      case 3:
        return DEBUG;
      default:
        return null;
    }
  }
}
