/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package itdelatrisu.craq.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * Object envelope.
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2017-04-24")
public class CraqObject implements org.apache.thrift.TBase<CraqObject, CraqObject._Fields>, java.io.Serializable, Cloneable, Comparable<CraqObject> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CraqObject");

  private static final org.apache.thrift.protocol.TField NULL_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("null_value", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RETURN_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("return_value", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CraqObjectStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CraqObjectTupleSchemeFactory();

  public java.nio.ByteBuffer null_value; // optional
  public int return_value; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NULL_VALUE((short)1, "null_value"),
    RETURN_VALUE((short)2, "return_value");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NULL_VALUE
          return NULL_VALUE;
        case 2: // RETURN_VALUE
          return RETURN_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RETURN_VALUE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.NULL_VALUE,_Fields.RETURN_VALUE};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NULL_VALUE, new org.apache.thrift.meta_data.FieldMetaData("null_value", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.RETURN_VALUE, new org.apache.thrift.meta_data.FieldMetaData("return_value", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CraqObject.class, metaDataMap);
  }

  public CraqObject() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CraqObject(CraqObject other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetNull_value()) {
      this.null_value = org.apache.thrift.TBaseHelper.copyBinary(other.null_value);
    }
    this.return_value = other.return_value;
  }

  public CraqObject deepCopy() {
    return new CraqObject(this);
  }

  @Override
  public void clear() {
    this.null_value = null;
    setReturn_valueIsSet(false);
    this.return_value = 0;
  }

  public byte[] getNull_value() {
    setNull_value(org.apache.thrift.TBaseHelper.rightSize(null_value));
    return null_value == null ? null : null_value.array();
  }

  public java.nio.ByteBuffer bufferForNull_value() {
    return org.apache.thrift.TBaseHelper.copyBinary(null_value);
  }

  public CraqObject setNull_value(byte[] null_value) {
    this.null_value = null_value == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(null_value.clone());
    return this;
  }

  public CraqObject setNull_value(java.nio.ByteBuffer null_value) {
    this.null_value = org.apache.thrift.TBaseHelper.copyBinary(null_value);
    return this;
  }

  public void unsetNull_value() {
    this.null_value = null;
  }

  /** Returns true if field null_value is set (has been assigned a value) and false otherwise */
  public boolean isSetNull_value() {
    return this.null_value != null;
  }

  public void setNull_valueIsSet(boolean value) {
    if (!value) {
      this.null_value = null;
    }
  }

  public int getReturn_value() {
    return this.return_value;
  }

  public CraqObject setReturn_value(int return_value) {
    this.return_value = return_value;
    setReturn_valueIsSet(true);
    return this;
  }

  public void unsetReturn_value() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RETURN_VALUE_ISSET_ID);
  }

  /** Returns true if field return_value is set (has been assigned a value) and false otherwise */
  public boolean isSetReturn_value() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RETURN_VALUE_ISSET_ID);
  }

  public void setReturn_valueIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RETURN_VALUE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case NULL_VALUE:
      if (value == null) {
        unsetNull_value();
      } else {
        if (value instanceof byte[]) {
          setNull_value((byte[])value);
        } else {
          setNull_value((java.nio.ByteBuffer)value);
        }
      }
      break;

    case RETURN_VALUE:
      if (value == null) {
        unsetReturn_value();
      } else {
        setReturn_value((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NULL_VALUE:
      return getNull_value();

    case RETURN_VALUE:
      return getReturn_value();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NULL_VALUE:
      return isSetNull_value();
    case RETURN_VALUE:
      return isSetReturn_value();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CraqObject)
      return this.equals((CraqObject)that);
    return false;
  }

  public boolean equals(CraqObject that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_null_value = true && this.isSetNull_value();
    boolean that_present_null_value = true && that.isSetNull_value();
    if (this_present_null_value || that_present_null_value) {
      if (!(this_present_null_value && that_present_null_value))
        return false;
      if (!this.null_value.equals(that.null_value))
        return false;
    }

    boolean this_present_return_value = true && this.isSetReturn_value();
    boolean that_present_return_value = true && that.isSetReturn_value();
    if (this_present_return_value || that_present_return_value) {
      if (!(this_present_return_value && that_present_return_value))
        return false;
      if (this.return_value != that.return_value)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetNull_value()) ? 131071 : 524287);
    if (isSetNull_value())
      hashCode = hashCode * 8191 + null_value.hashCode();

    hashCode = hashCode * 8191 + ((isSetReturn_value()) ? 131071 : 524287);
    if (isSetReturn_value())
      hashCode = hashCode * 8191 + return_value;

    return hashCode;
  }

  @Override
  public int compareTo(CraqObject other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetNull_value()).compareTo(other.isSetNull_value());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNull_value()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.null_value, other.null_value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReturn_value()).compareTo(other.isSetReturn_value());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReturn_value()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.return_value, other.return_value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CraqObject(");
    boolean first = true;

    if (isSetNull_value()) {
      sb.append("null_value:");
      if (this.null_value == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.null_value, sb);
      }
      first = false;
    }
    if (isSetReturn_value()) {
      if (!first) sb.append(", ");
      sb.append("return_value:");
      sb.append(this.return_value);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CraqObjectStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CraqObjectStandardScheme getScheme() {
      return new CraqObjectStandardScheme();
    }
  }

  private static class CraqObjectStandardScheme extends org.apache.thrift.scheme.StandardScheme<CraqObject> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CraqObject struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NULL_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.null_value = iprot.readBinary();
              struct.setNull_valueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RETURN_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.return_value = iprot.readI32();
              struct.setReturn_valueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CraqObject struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.null_value != null) {
        if (struct.isSetNull_value()) {
          oprot.writeFieldBegin(NULL_VALUE_FIELD_DESC);
          oprot.writeBinary(struct.null_value);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetReturn_value()) {
        oprot.writeFieldBegin(RETURN_VALUE_FIELD_DESC);
        oprot.writeI32(struct.return_value);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CraqObjectTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CraqObjectTupleScheme getScheme() {
      return new CraqObjectTupleScheme();
    }
  }

  private static class CraqObjectTupleScheme extends org.apache.thrift.scheme.TupleScheme<CraqObject> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CraqObject struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetNull_value()) {
        optionals.set(0);
      }
      if (struct.isSetReturn_value()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetNull_value()) {
        oprot.writeBinary(struct.null_value);
      }
      if (struct.isSetReturn_value()) {
        oprot.writeI32(struct.return_value);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CraqObject struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.null_value = iprot.readBinary();
        struct.setNull_valueIsSet(true);
      }
      if (incoming.get(1)) {
        struct.return_value = iprot.readI32();
        struct.setReturn_valueIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

